caravelInstall.installd(homeDir .. "/.config/fish")
caravelInstall.installd(homeDir .. "/.config/fish/conf.d")
caravelInstall.install(644, "dotfiles/conf.d/*.fish", homeDir .. "/.config/fish/conf.d")
caravelInstall.installd(homeDir .. ".config/fish/completions")
caravelInstall.install(644, "dotfiles/completions/*.fish", homeDir .. "/.config/fish/conf.d")
caravelInstall.installd(homeDir .. "/fish/functions")
caravelInstall.install(644, "dotfiles/config.fish",homeDir .. "/.config/fish/config.fish")
caravelInstall.install(644, "dotfiles/fish_plugins", homeDir .. "/.config/fish/fish_plugins")
caravelInstall.install(644, "dotfiles/LICENSE", homeDir .. "/.config/fish/LICENSE")
caravelInstall.print("Installation complete.")
caravelInstall.print("Run \"fisher update\" to install all of the required packages.")
